version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_app
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: always

  api:
    build:
      context: .
    env_file:
      - .env
    container_name: api
    restart: always
    command: bash -c "make run_api_prod"
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  admin:
    build:
      context: .
    env_file:
      - .env
    container_name: admin
    restart: always
    command: bash -c "make run_admin"
    ports:
      - 5000:5000
    depends_on:
      - db
      - api
  
  celery:
    restart: always
    build: .
    command: bash -c "make run_celery"
    depends_on:
      - redis
      - api
      
  
  celery_sheduel:
    restart: always
    build: .
    command: bash -c "make run_celery_beat" 
    depends_on:
     - redis
     - celery

volumes:
  db_data: