"""empty message

Revision ID: 23369c09217e
Revises: 
Create Date: 2024-01-30 15:03:07.543228

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '23369c09217e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'financial_indebtedness',
        sa.Column('fio', sa.String(length=255), nullable=False),
        sa.Column('personal_number', sa.String(length=10), nullable=False),
        sa.Column('contract_number', sa.String(length=255), nullable=False),
        sa.Column('sum', sa.Float(decimal_return_scale=2), nullable=False),
        sa.Column('status', sa.Boolean(), nullable=False),
        sa.Column('file_created_time', sa.TIMESTAMP(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_indebtedness')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_indebtedness')
    # ### end Alembic commands ###
