"""empty message

Revision ID: 63abb5ac71eb
Revises: ee6efa17b4ec
Create Date: 2024-02-12 15:52:43.754741

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '63abb5ac71eb'
down_revision: Union[str, None] = 'ee6efa17b4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'students',
        sa.Column('fio', sa.String(length=255), nullable=False),
        sa.Column('personal_number', sa.String(length=10), nullable=False),
        sa.Column('group', sa.String(length=10), nullable=False),
        sa.Column('program', sa.String(length=100), nullable=False),
        sa.Column('form', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('api_key', sa.String(length=255), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    )
    op.create_index(op.f('ix_students_personal_number'), 'students', ['personal_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_personal_number'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
