"""empty message

Revision ID: 88e4e880d714
Revises: 
Create Date: 2024-02-28 09:27:40.028869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e4e880d714'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_indebtedness',
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('personal_number', sa.String(length=10), nullable=False),
    sa.Column('contract_number', sa.String(length=255), nullable=False),
    sa.Column('sum', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('file_created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_indebtedness'))
    )
    op.create_index(op.f('ix_financial_indebtedness_personal_number'), 'financial_indebtedness', ['personal_number'], unique=False)
    op.create_table('students',
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('personal_number', sa.String(length=10), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=False),
    sa.Column('program', sa.String(length=100), nullable=False),
    sa.Column('form', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index(op.f('ix_students_personal_number'), 'students', ['personal_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_personal_number'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_financial_indebtedness_personal_number'), table_name='financial_indebtedness')
    op.drop_table('financial_indebtedness')
    # ### end Alembic commands ###
