"""empty message

Revision ID: ee6efa17b4ec
Revises: 
Create Date: 2024-02-09 15:40:54.527567

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee6efa17b4ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'financial_indebtedness',
        sa.Column('fio', sa.String(length=255), nullable=False),
        sa.Column('personal_number', sa.String(length=10), nullable=False),
        sa.Column('contract_number', sa.String(length=255), nullable=False),
        sa.Column('sum', sa.Float(decimal_return_scale=2), nullable=False),
        sa.Column('status', sa.Boolean(), server_default='1', nullable=False),
        sa.Column('file_created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_indebtedness')),
    )
    op.create_index(
        op.f('ix_financial_indebtedness_personal_number'), 'financial_indebtedness', ['personal_number'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_indebtedness_personal_number'), table_name='financial_indebtedness')
    op.drop_table('financial_indebtedness')
    # ### end Alembic commands ###
